window.MAUS_CONTENT = {
  "schema": 1,
  "settings": {
    "brand": "MAUS TIER LISTS",
    "tagline": "offline · online · música",
    "documentTitle": "Tier List de Maus",
    "description": "Videojuegos, críticas y músicas que se quedan conmigo.",
    "logo": "assets/brand/simba.jpg",
    "shareImage": "social-preview-v4.6.3.jpg",
    "homeRoute": "tierlist",
    "navOffline": "OFFLINE",
    "navOnline": "ONLINE",
    "navMusic": "Resonancias",
    "navReviews": "Reviews",
    "navFeatures": "Features",
    "navPresentation": "Modo presentación",
    "navAppearance": "Apariencia",
    "offlineEyebrow": "TIER LIST · OFFLINE",
    "offlineTitle": "Mi ranking offline,\ncon cada review detrás.",
    "offlineLead": "Campañas, aventuras y experiencias principalmente offline. Pulsa cualquier juego para abrir directamente su ficha.",
    "offlineNote": "Dentro de un mismo tier, cuanto más a la izquierda está, más arriba lo tengo.",
    "offlineStats": "ordenados según mi tier list offline actual",
    "onlineEyebrow": "TIER LIST · ONLINE",
    "onlineTitle": "Mi ranking online,\nseparado del resto.",
    "onlineLead": "Aquí van únicamente juegos cuyo núcleo está en el multijugador, competitivo o cooperativo online. Su ranking es independiente del offline.",
    "onlineNote": "La posición de un juego online no afecta a su posición en la tier list offline.",
    "onlineStats": "ranking multijugador independiente",
    "readRanking": "▶ Leer ranking de arriba a abajo",
    "offlineReviewsButton": "Ver reviews offline",
    "onlineReviewsButton": "Ver reviews online",
    "offlineSwitch": "Campañas · single player",
    "onlineSwitch": "Competitivo · coop · multijugador",
    "musicSwitch": "Una colección para escuchar y leer",
    "offlineReviewsTitle": "Mis juegos offline.",
    "offlineReviewsLead": "Campañas y experiencias principalmente offline.",
    "onlineReviewsTitle": "Mis juegos online.",
    "onlineReviewsLead": "Biblioteca independiente para juegos multijugador y competitivos.",
    "reviewSearch": "Buscar una review…",
    "musicEyebrow": "EL ARCHIVO SONORO DE MAUS",
    "musicTitle": "Resonancias",
    "musicSubtitle": "Hay músicas que no se quedan en el juego.",
    "musicLead": "Un lugar para detenerme en las músicas de videojuegos que me encantan. Escucharlas, hablar de ellas y volver a lo que me hacen sentir.",
    "musicEmptyTitle": "La primera escucha está por llegar.",
    "musicEmptyText": "Este archivo irá creciendo con mis músicas favoritas. Cada una tendrá su espacio, su historia y una escucha sin prisas.",
    "musicFooter": "Una colección personal. Sin notas. Sin puestos. Solo música.",
    "musicSearch": "Buscar música, juego o compositor…",
    "offlinePresentationTitle": "Mi ranking de videojuegos offline",
    "offlinePresentationLead": "Campañas, aventuras y experiencias principalmente offline.",
    "onlinePresentationTitle": "Mi ranking de videojuegos online",
    "onlinePresentationLead": "Experiencias multijugador, competitivas y cooperativas.",
    "presentationFooter": "Dentro de cada tier, el orden va de izquierda a derecha.",
    "featuresTitle": "Qué hay aquí y dónde tocar.",
    "featuresLead": "Una guía rápida para saber qué puedes explorar sin tener que descubrir cada función por accidente.",
    "musicKicker": "VIDEOJUEGOS / MÚSICA / MEMORIA",
    "musicExplore": "Explorar la colección",
    "musicShelf": "La colección",
    "musicFeatured": "EN PRIMER PLANO",
    "musicEmptyArtLabel": "UNA ESCUCHA A LA VEZ",
    "musicEmptyArtText": "El sonido también cuenta historias.",
    "musicListeningNotes": "NOTAS DE ESCUCHA",
    "offlineHeroImage": "",
    "onlineHeroImage": "",
    "defaultTheme": "default",
    "accent": "#64dfb4",
    "maxWidth": "1220",
    "musicPaper": "#eee7d9",
    "musicInk": "#25231f",
    "musicAccent": "#9b4225",
    "musicColumns": "3"
  },
  "tracks": [],
  "features": [
    {
      "title": "Dos rankings, dos formas de jugar",
      "text": "Offline y online tienen su propio ranking, sus reviews y su recorrido.",
      "route": "tierlist",
      "label": "Explorar los juegos"
    },
    {
      "title": "Un archivo para la música",
      "text": "Fichas dedicadas a músicas de videojuegos: escuchar, leer y descubrir sus detalles, sin puntuaciones.",
      "route": "music",
      "label": "Abrir el archivo sonoro"
    },
    {
      "title": "Una escena para cada juego",
      "text": "Fondos, ambiente y música acompañan las críticas. Desde Apariencia puedes elegir todos los efectos, ambiente reducido o un fondo sin efectos.",
      "route": "games/offline",
      "label": "Explorar las reviews"
    },
    {
      "title": "Escucha a tu ritmo",
      "text": "Pausa y reanuda sin perder la posición, ajusta el volumen o salta a otra parte de la canción. Los efectos musicales siguen el instante que estás escuchando.",
      "route": "music",
      "label": "Escuchar"
    },
    {
      "title": "Presentación y fondo",
      "text": "Modo presentación reúne las portadas del ranking. Ver fondo oculta la interfaz para disfrutar de la escena.",
      "route": "tierlist",
      "label": "Volver al ranking"
    }
  ]
};
