(function () {
  'use strict';
  const model=window.MausContentModel;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=value=>JSON.parse(JSON.stringify(value));
  function create(options) {
    const root=document.getElementById('contentEditorRoot');
    let data=model.defaults(),view='games',selected='',group='Identidad',previewRoute='tierlist',previewTimer;
    const pending=new Map(),urls=new Map();
    const current=()=>data.tracks.find(t=>t.id===selected);
    const keyFor=(id,kind)=>id+'::'+kind;
    function clearFiles(){for(const url of urls.values())URL.revokeObjectURL(url);pending.clear();urls.clear();}
    function change(){
      options.onChange();
      if(view==='music'){
        const count=root.querySelector('.content-navigation>.field-help');
        if(count)count.textContent=data.tracks.length+' fichas · '+data.tracks.filter(t=>t.published).length+' publicadas';
        for(const button of root.querySelectorAll('[data-select-track]')){
          const track=data.tracks.find(t=>t.id===button.dataset.selectTrack);
          if(track){button.querySelector('strong').textContent=track.title;button.querySelector('small').textContent=(track.published?'Publicada':'Borrador')+' · '+(track.game||'Sin juego');}
        }
      }
      clearTimeout(previewTimer);previewTimer=setTimeout(sendPreview,220);
    }
    function sendPreview(){const frame=root.querySelector('iframe');if(!frame?.contentWindow)return;const preview=clone(data);for(const [key,url] of urls){const [id,kind]=key.split('::');if(id==='settings')preview.settings[kind]=url;else {const item=preview.tracks.find(t=>t.id===id);if(item)item[kind]=url;}}frame.contentWindow.postMessage({type:'maus-editor-preview',content:preview,previewTrack:view==='music'?selected:null},location.origin);}
    function field(label,key,value,type='text',attrs=''){return `<label class="field"><span>${esc(label)}</span>${type==='textarea'?`<textarea rows="4" ${attrs} data-track-key="${esc(key)}">${esc(value)}</textarea>`:`<input type="${type}" ${attrs} data-track-key="${esc(key)}" value="${esc(value)}">`}</label>`}
    function fileField(label,id,kind,value){const url=urls.get(keyFor(id,kind))||value;return `<div class="content-file"><strong>${esc(label)}</strong>${kind==='audio'?url?`<audio controls preload="none" src="${esc(url)}"></audio>`:'':url?`<img src="${esc(url)}" alt="Vista previa de ${esc(label)}">`:''}<label class="field"><span>Archivo ${pending.has(keyFor(id,kind))?'preparado: '+esc(pending.get(keyFor(id,kind)).name):'nuevo'}</span><input type="file" data-asset-id="${esc(id)}" data-asset-kind="${esc(kind)}" accept="${kind==='audio'?'.mp3,audio/mpeg':'.jpg,.jpeg,.png,.webp,.avif'}"></label><small>${esc(value||'Sin archivo')}</small>${pending.has(keyFor(id,kind))?`<button type="button" class="ghost-button" data-unstage="${esc(keyFor(id,kind))}">Deshacer selección</button>`:''}${value?`<button type="button" class="text-link" data-remove-media="${esc(keyFor(id,kind))}">Quitar ${esc(label.toLowerCase())}</button>`:''}</div>`}
    function trackForm(){const t=current();if(!t)return '<div class="content-empty"><h2>Tu archivo musical empieza aquí.</h2><p>Añade una ficha para una música que te encante. No tiene nota ni posición en un ranking.</p><button type="button" class="primary-button" data-add-track>＋ Añadir música</button></div>';
      const games=options.getGames();return `<div class="content-form-head"><div><span class="eyebrow">FICHA MUSICAL</span><h2>${esc(t.title)}</h2><small>Enlace: #music/${esc(t.id)}</small></div><button type="button" class="ghost-button" data-delete-track>Eliminar ficha</button></div>
      <div class="content-toggles"><label><input type="checkbox" data-track-key="published" ${t.published?'checked':''}> Publicar ficha</label><label><input type="checkbox" data-track-key="featured" ${t.featured?'checked':''}> En primer plano</label></div>
      ${field('Título de la música','title',t.title)}
      <div class="form-grid">${field('Videojuego','game',t.game)}${field('Compositor / intérprete','composer',t.composer)}${field('Álbum / banda sonora','album',t.album)}${field('Año','year',t.year)}</div>
      ${field('Entradilla: qué hace especial esta música','excerpt',t.excerpt,'textarea')}${field('Etiquetas, separadas por comas','tags',(t.tags||[]).join(', '))}
      <div class="form-card"><h3>Relacionar con un juego de la web</h3><label class="field"><span>Juego y ambiente</span><select data-track-key="gameId"><option value="">Sin juego vinculado</option>${games.map(g=>`<option value="${esc(g.id)}" ${t.gameId===g.id?'selected':''}>${esc(g.title)}</option>`).join('')}</select></label><button type="button" class="ghost-button" data-import-game ${t.gameId?'':'disabled'}>Usar su portada y su música</button><p class="field-help">Vincula la review y permite recuperar el ambiente del juego. Puedes usar un MP3 y una portada distintos para cada ficha.</p></div>
      <div class="content-media">${fileField('Portada',t.id,'cover',t.cover)}${fileField('Fondo',t.id,'background',t.background)}${fileField('MP3',t.id,'audio',t.audio)}</div>
      ${field('Segundo inicial de reproducción','startAt',t.startAt||0,'number','min="0" step="0.1"')}
      <div class="content-form-head"><h3>Texto de la ficha</h3><button type="button" class="ghost-button" data-add-section>＋ Añadir sección</button></div>
      <p class="field-help">Separa párrafos con una línea en blanco. Puedes usar **negrita** y *cursiva*.</p>
      <div class="content-sections">${(t.sections||[]).map((section,i)=>`<section class="form-card"><div class="content-section-actions"><strong>Sección ${i+1}</strong><button type="button" class="ghost-button" data-section-move="${i}" data-direction="-1" ${i===0?'disabled':''} aria-label="Subir sección ${i+1}">↑</button><button type="button" class="ghost-button" data-section-move="${i}" data-direction="1" ${i===t.sections.length-1?'disabled':''} aria-label="Bajar sección ${i+1}">↓</button><button type="button" class="ghost-button" data-section-delete="${i}">Quitar</button></div><label class="field"><span>Título</span><input data-section-index="${i}" data-section-key="title" value="${esc(section.title)}"></label><label class="field"><span>Texto</span><textarea rows="7" data-section-index="${i}" data-section-key="paragraphs">${esc((section.paragraphs||[]).join('\n\n'))}</textarea></label></section>`).join('')}</div>
      <div class="content-section-actions"><button type="button" class="ghost-button" data-move-track="-1">← Antes en la colección</button><button type="button" class="ghost-button" data-move-track="1">Después en la colección →</button><button type="button" class="ghost-button" data-duplicate-track>Duplicar como borrador</button></div>`;
    }
    function settingForm(){const fields=model.fields.filter(f=>f[0]===group);return `<div class="content-form-head"><h2>${esc(group)}</h2><span class="id-badge">EDICIÓN VISUAL</span></div><div class="content-settings">${fields.map(([,key,label,,type,choices])=>type==='asset'?fileField(label,'settings',key,data.settings[key]):`<label class="field"><span>${esc(label)}</span>${type==='textarea'?`<textarea rows="4" data-setting="${key}">${esc(data.settings[key])}</textarea>`:type==='select'?`<select data-setting="${key}">${choices.map(v=>`<option value="${v}" ${data.settings[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select>`:`<input type="${type||'text'}" data-setting="${key}" value="${esc(data.settings[key])}" ${type==='number'?'min="960" max="1800"':''}>`}</label>`).join('')}</div>${group==='Guía'?`<div class="content-form-head"><h3>Tarjetas de la guía</h3><button type="button" class="ghost-button" data-add-feature>＋ Añadir tarjeta</button></div>${data.features.map((item,i)=>`<section class="form-card"><div class="content-section-actions"><strong>Tarjeta ${i+1}</strong><button type="button" class="ghost-button" data-remove-feature="${i}">Eliminar</button></div>${['title','text','label'].map((k,j)=>`<label class="field"><span>${['Título','Descripción','Texto del botón'][j]}</span><textarea rows="${k==='text'?4:1}" data-feature="${i}" data-feature-key="${k}">${esc(item[k])}</textarea></label>`).join('')}<label class="field"><span>Destino del botón</span><select data-feature="${i}" data-feature-key="route">${['tierlist','online','music','games/offline','games/online'].map(r=>`<option value="${r}" ${item.route===r?'selected':''}>${r}</option>`).join('')}</select></label></section>`).join('')}`:''}`;}
    function render(){if(view==='games')return;const groups=[...new Set(model.fields.map(f=>f[0]))];root.innerHTML=`<div class="content-editor-layout"><aside class="content-navigation">${view==='music'?`<button type="button" class="primary-button" data-add-track>＋ Añadir música</button><p class="field-help">${data.tracks.length} fichas · ${data.tracks.filter(t=>t.published).length} publicadas</p>${data.tracks.map(t=>`<button type="button" data-select-track="${esc(t.id)}" class="content-nav-button ${t.id===selected?'active':''}"><strong>${esc(t.title)}</strong><small>${t.published?'Publicada':'Borrador'} · ${esc(t.game||'Sin juego')}</small></button>`).join('')}`:groups.map(g=>`<button type="button" data-setting-group="${esc(g)}" class="content-nav-button ${g===group?'active':''}">${esc(g)}</button>`).join('')}</aside><section class="content-edit-form">${view==='music'?trackForm():settingForm()}</section><aside class="content-preview"><div class="content-preview-head"><strong>Vista previa</strong><select id="contentPreviewRoute" aria-label="Página de vista previa">${[['tierlist','Portada offline'],['online','Portada online'],['music','Archivo musical'],['features','Guía'],...(selected?[['music/'+selected,'Ficha actual']]:[])].map(([r,l])=>`<option value="${esc(r)}" ${r===previewRoute?'selected':''}>${l}</option>`).join('')}</select></div><div class="content-preview-device"><iframe title="Vista previa de los cambios sin publicar" src="./?preview=1#${esc(previewRoute)}"></iframe></div><p class="field-help">La música no se inicia automáticamente en esta vista. Los borradores solo aparecen aquí hasta que los publiques.</p></aside></div>`;root.querySelector('iframe').addEventListener('load',sendPreview);}
    function setView(next){view=next;document.querySelector('.game-sidebar').hidden=view!=='games';document.getElementById('gameForm').hidden=view!=='games';root.hidden=view==='games';document.getElementById('editorPanel').classList.toggle('content-editing',view!=='games');document.querySelectorAll('[data-editor-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.editorView===view)));if(view!=='games'){document.getElementById('editorTitle').textContent=view==='music'?'Archivo musical':'Portadas y web';document.getElementById('editorSubtitle').textContent='Edita, comprueba la vista previa y publica todos los cambios juntos.';previewRoute=view==='music'?(selected?'music/'+selected:'music'):'tierlist';render();}else options.onGamesView();}
    function newId(){return 'musica-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6)}
    function addTrack(from){const t=from?clone(from):{title:'Nueva música',game:'',gameId:'',composer:'',album:'',year:'',excerpt:'',tags:[],cover:'',background:'',audio:'',startAt:0,sections:[{title:'Lo que me hace sentir',paragraphs:[]}]};t.id=newId();t.published=false;t.featured=false;data.tracks.push(t);selected=t.id;previewRoute='music/'+selected;render();change();}
    root.addEventListener('input',event=>{const el=event.target,t=current();if(el.dataset.trackKey&&t){const k=el.dataset.trackKey;t[k]=el.type==='checkbox'?el.checked:k==='tags'?el.value.split(',').map(s=>s.trim()).filter(Boolean):el.value;if(k==='featured'&&t.featured)data.tracks.forEach(x=>{if(x!==t)x.featured=false});const nav=root.querySelector('[data-select-track="'+t.id+'"] strong');if(nav)nav.textContent=t.title;if(k==='gameId'){const b=root.querySelector('[data-import-game]');if(b)b.disabled=!t.gameId;}}else if(el.dataset.setting)data.settings[el.dataset.setting]=el.value;else if(el.dataset.sectionKey&&t){const section=t.sections[Number(el.dataset.sectionIndex)];section[el.dataset.sectionKey]=el.dataset.sectionKey==='paragraphs'?el.value.replace(/\r/g,'').split(/\n\s*\n/).filter(x=>x.trim()):el.value;}else if(el.dataset.featureKey)data.features[Number(el.dataset.feature)][el.dataset.featureKey]=el.value;else return;change();});
    root.addEventListener('change',event=>{const el=event.target;if(el.id==='contentPreviewRoute'){previewRoute=el.value;render();return}if(!el.dataset.assetKind)return;const file=el.files?.[0];if(!file)return;const audio=el.dataset.assetKind==='audio';if(file.size>(audio?50:15)*1024*1024||!(audio?/\.mp3$/i:/\.(jpe?g|png|webp|avif)$/i).test(file.name)){options.notice('Elige un '+(audio?'MP3 de hasta 50 MB.':'JPG, PNG, WEBP o AVIF de hasta 15 MB.'),true);el.value='';return}const key=keyFor(el.dataset.assetId,el.dataset.assetKind);if(urls.has(key))URL.revokeObjectURL(urls.get(key));pending.set(key,file);urls.set(key,URL.createObjectURL(file));render();change();});
    root.addEventListener('click',event=>{const el=event.target.closest('button');if(!el)return;const t=current();
      if(el.hasAttribute('data-add-track')){addTrack();return}
      if(el.dataset.selectTrack){selected=el.dataset.selectTrack;previewRoute='music/'+selected;render();return}
      if(el.dataset.settingGroup){group=el.dataset.settingGroup;previewRoute=group.startsWith('Música')?'music':group==='Guía'?'features':group.includes('online')?'online':'tierlist';render();return}
      if(el.hasAttribute('data-duplicate-track')&&t){addTrack(t);return}
      if(el.hasAttribute('data-delete-track')&&t){if(!confirm('¿Eliminar la ficha «'+t.title+'»? Se aplicará cuando publiques.'))return;data.tracks=data.tracks.filter(x=>x!==t);for(const key of [...pending.keys()])if(key.startsWith(t.id+'::')){pending.delete(key);URL.revokeObjectURL(urls.get(key));urls.delete(key)}selected=data.tracks[0]?.id||'';previewRoute=selected?'music/'+selected:'music';}
      else if(el.hasAttribute('data-import-game')&&t){const g=options.getGames().find(x=>x.id===t.gameId);if(g){const media=options.getGameMedia(g);t.game=g.title;t.cover=media.cover;t.background='';t.audio=media.music.src||'';t.composer=media.music.composer||'';t.startAt=media.music.startAt||0;if(t.title==='Nueva música')t.title=media.music.title||g.title;}}
      else if(el.hasAttribute('data-add-section')&&t)t.sections.push({title:'Nueva sección',paragraphs:[]});
      else if(el.dataset.sectionDelete!==undefined&&t)t.sections.splice(Number(el.dataset.sectionDelete),1);
      else if(el.dataset.sectionMove!==undefined&&t){const i=+el.dataset.sectionMove,j=i+(+el.dataset.direction);if(j>=0&&j<t.sections.length)[t.sections[i],t.sections[j]]=[t.sections[j],t.sections[i]];}
      else if(el.dataset.moveTrack&&t){const i=data.tracks.indexOf(t),j=i+(+el.dataset.moveTrack);if(j>=0&&j<data.tracks.length)[data.tracks[i],data.tracks[j]]=[data.tracks[j],data.tracks[i]];}
      else if(el.dataset.unstage){URL.revokeObjectURL(urls.get(el.dataset.unstage));urls.delete(el.dataset.unstage);pending.delete(el.dataset.unstage);}
      else if(el.dataset.removeMedia){const [id,kind]=el.dataset.removeMedia.split('::');if(id==='settings')data.settings[kind]='';else data.tracks.find(x=>x.id===id)[kind]='';if(urls.has(el.dataset.removeMedia))URL.revokeObjectURL(urls.get(el.dataset.removeMedia));urls.delete(el.dataset.removeMedia);pending.delete(el.dataset.removeMedia);}
      else if(el.hasAttribute('data-add-feature'))data.features.push({title:'Nueva tarjeta',text:'',label:'Explorar',route:'tierlist'});
      else if(el.dataset.removeFeature!==undefined)data.features.splice(+el.dataset.removeFeature,1);
      else return;
      render();change();
    });
    for(const tab of document.querySelectorAll('[data-editor-view]'))tab.addEventListener('click',()=>setView(tab.dataset.editorView));
    function validate(){const check=clone(data);for(const [key] of pending){const [id,kind]=key.split('::');if(id!=='settings'){const t=check.tracks.find(x=>x.id===id);if(t)t[kind]='assets/pending.'+(kind==='audio'?'mp3':'jpg');}}model.validate(check);}
    async function prepare(version,upload){const next=clone(data);for(const [key,file] of pending){const [id,kind]=key.split('::'),ext=file.name.split('.').pop().toLowerCase().replace('jpeg','jpg'),path='assets/'+(id==='settings'?'site':'music')+'/'+id+'-'+kind+'-v'+version.replaceAll('.','-')+'.'+ext;await upload(path,file);if(id==='settings')next.settings[kind]=path;else{const t=next.tracks.find(t=>t.id===id);if(t)t[kind]=path;}}model.validate(next);return next;}
    return {snapshot:()=>clone(data),hasPendingFiles:()=>pending.size>0,validate,prepare,
      load(value){clearFiles();data=model.normalize(value);selected=data.tracks[0]?.id||'';if(view!=='games')setView(view);},
      accept(value){clearFiles();data=model.normalize(value);if(view!=='games')render();},
      refresh(){if(view!=='games')setView(view);},
      reset(){clearFiles();data=model.defaults();selected='';setView('games');},
      removeGameReference(id){for(const track of data.tracks)if(track.gameId===id)track.gameId='';},
      setView
    };
  }
  window.MausContentEditor={create};
})();
