(function () {
  'use strict';
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lines=value=>esc(value).replace(/\n/g,'<br>');
  const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function artwork(track,large=false){return `<div class="record-art${large?' record-art-large':''}">${track?.cover?`<img src="${esc(track.cover)}" alt="" ${large?'':'loading="lazy"'}>`:'<div class="record-disc" aria-hidden="true"><i></i><span>MAUS<br>ARCHIVE</span></div>'}<span class="record-corner" aria-hidden="true">♫</span></div>`}
  function card(track,index){return `<a class="music-card" href="#music/${encodeURIComponent(track.id)}">${artwork(track)}<div class="music-card-meta"><span>${esc(track.game)}</span><span>${esc(track.year||'')}</span></div><h2>${esc(track.title)}</h2><p>${esc(track.excerpt||track.composer||'Abrir ficha y escuchar')}</p><span class="music-card-link">Escuchar y leer <span aria-hidden="true">↗</span></span></a>`}
  function collection(content){const s=content.settings,tracks=content.tracks.filter(t=>t.published);const featured=tracks.find(t=>t.featured)||tracks[0];return `<div class="page music-page music-collection">
    <div class="music-masthead"><span>${esc(s.musicEyebrow)}</span><span>ARCHIVO PERSONAL · ${String(tracks.length).padStart(2,'0')} ${tracks.length===1?'FICHA':'FICHAS'}</span></div>
    <section class="music-intro"><div><p class="music-small">${esc(s.musicKicker)}</p><h1>${lines(s.musicTitle)}</h1><h2>${lines(s.musicSubtitle)}</h2><p class="music-intro-copy">${lines(s.musicLead)}</p><a class="music-text-link" href="#music" data-music-scroll>${esc(s.musicExplore)} <span aria-hidden="true">↓</span></a></div>
    <div class="music-featured">${featured?`<a href="#music/${encodeURIComponent(featured.id)}" aria-label="Escuchar ${esc(featured.title)}">${artwork(featured,true)}<div class="music-featured-caption"><span>${esc(s.musicFeatured)}</span><strong>${esc(featured.title)}</strong><small>${esc(featured.game)}</small></div></a>`:`${artwork(null,true)}<div class="music-featured-caption"><span>${esc(s.musicEmptyArtLabel)}</span><strong>${esc(s.musicEmptyArtText)}</strong></div>`}</div></section>
    <section id="musicCollection" class="music-shelf"><div class="music-shelf-head"><h2>${esc(s.musicShelf)}<span aria-hidden="true"> / </span><small>${String(tracks.length).padStart(2,'0')}</small></h2>${tracks.length?`<label class="music-search"><span class="sr-only">${esc(s.musicSearch)}</span><input id="musicSearch" type="search" placeholder="${esc(s.musicSearch)}" autocomplete="off"></label>`:''}</div>
    <div id="musicGrid" class="music-grid">${tracks.length?tracks.map(card).join(''):`<div class="music-empty"><span aria-hidden="true">01 —</span><h3>${esc(s.musicEmptyTitle)}</h3><p>${lines(s.musicEmptyText)}</p></div>`}</div><p id="musicSearchCount" class="music-search-count" role="status"></p></section>
    <footer class="music-colophon"><span>${esc(s.musicFooter)}</span><span>${esc(s.brand)}</span></footer></div>`}
  function detail(track,content){const tracks=content.tracks.filter(t=>t.published),index=tracks.findIndex(t=>t.id===track.id),previous=tracks[index-1],next=tracks[index+1];return `<div class="page music-page music-detail">
    <div class="music-masthead"><a href="#music">← ${esc(content.settings.musicTitle)}</a><span>FICHA SONORA · ${String(index+1).padStart(2,'0')}</span></div>
    <section class="music-detail-hero"><div class="music-detail-art">${artwork(track,true)}</div><div class="music-detail-heading"><span class="music-small">${esc(track.game)}</span><h1>${esc(track.title)}</h1><p class="music-deck">${lines(track.excerpt||'')}</p><div class="music-credits">${[['Composición',track.composer],['Álbum',track.album],['Año',track.year]].filter(x=>x[1]).map(([k,v])=>`<span><small>${k}</small>${esc(v)}</span>`).join('')}</div><button type="button" class="music-play-button" data-music-play aria-pressed="false">▶ Reproducir</button><p class="music-tags">${(track.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</p></div></section>
    <div class="music-essay-layout"><aside class="music-margin-note"><span>${esc(content.settings.musicListeningNotes)}</span><p>${esc(track.game)}</p>${track.gameId?`<a href="#game/${encodeURIComponent(track.gameId)}">La review del juego ↗</a>`:''}</aside><article class="music-essay">${window.MausReviewRenderer.render(track.sections||[],{idPrefix:'music-'+track.id})}</article></div>
    <nav class="music-next" aria-label="Otras músicas">${previous?`<a href="#music/${encodeURIComponent(previous.id)}"><small>← ESCUCHA ANTERIOR</small><strong>${esc(previous.title)}</strong></a>`:'<span></span>'}${next?`<a href="#music/${encodeURIComponent(next.id)}"><small>SIGUIENTE ESCUCHA →</small><strong>${esc(next.title)}</strong></a>`:'<a href="#music">Volver a la colección ↗</a>'}</nav>
    <footer class="music-colophon"><span>${esc(content.settings.musicFooter)}</span><span>${esc(content.settings.brand)}</span></footer></div>`}
  function filter(content,query){const q=normalize(query);const tracks=content.tracks.filter(t=>t.published&&normalize([t.title,t.game,t.composer,...(t.tags||[])].join(' ')).includes(q));document.getElementById('musicGrid').innerHTML=tracks.length?tracks.map(card).join(''):'<p class="music-empty">No hay fichas que coincidan con tu búsqueda.</p>';document.getElementById('musicSearchCount').textContent=tracks.length+' fichas encontradas';}
  window.MausMusic={collection,detail,filter};
})();
